// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: forecaster.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ForecastRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MetricName      string                 `protobuf:"bytes,1,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	Values          []float64              `protobuf:"fixed64,2,rep,packed,name=values,proto3" json:"values,omitempty"`
	Timestamps      []float64              `protobuf:"fixed64,3,rep,packed,name=timestamps,proto3" json:"timestamps,omitempty"` // unix seconds
	Labels          map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Horizon         int32                  `protobuf:"varint,5,opt,name=horizon,proto3" json:"horizon,omitempty"`                                         // number of steps to predict
	IntervalSeconds float64                `protobuf:"fixed64,6,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"` // expected interval between points
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ForecastRequest) Reset() {
	*x = ForecastRequest{}
	mi := &file_forecaster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForecastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForecastRequest) ProtoMessage() {}

func (x *ForecastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forecaster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForecastRequest.ProtoReflect.Descriptor instead.
func (*ForecastRequest) Descriptor() ([]byte, []int) {
	return file_forecaster_proto_rawDescGZIP(), []int{0}
}

func (x *ForecastRequest) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *ForecastRequest) GetValues() []float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *ForecastRequest) GetTimestamps() []float64 {
	if x != nil {
		return x.Timestamps
	}
	return nil
}

func (x *ForecastRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ForecastRequest) GetHorizon() int32 {
	if x != nil {
		return x.Horizon
	}
	return 0
}

func (x *ForecastRequest) GetIntervalSeconds() float64 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

type ForecastPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     float64                `protobuf:"fixed64,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                     // predicted unix seconds
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`                             // point forecast
	LowerBound    float64                `protobuf:"fixed64,3,opt,name=lower_bound,json=lowerBound,proto3" json:"lower_bound,omitempty"` // 95% prediction interval lower
	UpperBound    float64                `protobuf:"fixed64,4,opt,name=upper_bound,json=upperBound,proto3" json:"upper_bound,omitempty"` // 95% prediction interval upper
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForecastPoint) Reset() {
	*x = ForecastPoint{}
	mi := &file_forecaster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForecastPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForecastPoint) ProtoMessage() {}

func (x *ForecastPoint) ProtoReflect() protoreflect.Message {
	mi := &file_forecaster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForecastPoint.ProtoReflect.Descriptor instead.
func (*ForecastPoint) Descriptor() ([]byte, []int) {
	return file_forecaster_proto_rawDescGZIP(), []int{1}
}

func (x *ForecastPoint) GetTimestamp() float64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ForecastPoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *ForecastPoint) GetLowerBound() float64 {
	if x != nil {
		return x.LowerBound
	}
	return 0
}

func (x *ForecastPoint) GetUpperBound() float64 {
	if x != nil {
		return x.UpperBound
	}
	return 0
}

type ForecastResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*ForecastPoint       `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "ok" or "error"
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForecastResponse) Reset() {
	*x = ForecastResponse{}
	mi := &file_forecaster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForecastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForecastResponse) ProtoMessage() {}

func (x *ForecastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forecaster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForecastResponse.ProtoReflect.Descriptor instead.
func (*ForecastResponse) Descriptor() ([]byte, []int) {
	return file_forecaster_proto_rawDescGZIP(), []int{2}
}

func (x *ForecastResponse) GetPoints() []*ForecastPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

func (x *ForecastResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ForecastResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_forecaster_proto protoreflect.FileDescriptor

const file_forecaster_proto_rawDesc = "" +
	"\n" +
	"\x10forecaster.proto\x12\n" +
	"forecaster\"\xab\x02\n" +
	"\x0fForecastRequest\x12\x1f\n" +
	"\vmetric_name\x18\x01 \x01(\tR\n" +
	"metricName\x12\x16\n" +
	"\x06values\x18\x02 \x03(\x01R\x06values\x12\x1e\n" +
	"\n" +
	"timestamps\x18\x03 \x03(\x01R\n" +
	"timestamps\x12?\n" +
	"\x06labels\x18\x04 \x03(\v2'.forecaster.ForecastRequest.LabelsEntryR\x06labels\x12\x18\n" +
	"\ahorizon\x18\x05 \x01(\x05R\ahorizon\x12)\n" +
	"\x10interval_seconds\x18\x06 \x01(\x01R\x0fintervalSeconds\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x85\x01\n" +
	"\rForecastPoint\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x01R\ttimestamp\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12\x1f\n" +
	"\vlower_bound\x18\x03 \x01(\x01R\n" +
	"lowerBound\x12\x1f\n" +
	"\vupper_bound\x18\x04 \x01(\x01R\n" +
	"upperBound\"\x82\x01\n" +
	"\x10ForecastResponse\x121\n" +
	"\x06points\x18\x01 \x03(\v2\x19.forecaster.ForecastPointR\x06points\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage2S\n" +
	"\n" +
	"Forecaster\x12E\n" +
	"\bForecast\x12\x1b.forecaster.ForecastRequest\x1a\x1c.forecaster.ForecastResponseB?Z=github.com/lohitkolluri/KubeWise/internal/agent/forecaster/pbb\x06proto3"

var (
	file_forecaster_proto_rawDescOnce sync.Once
	file_forecaster_proto_rawDescData []byte
)

func file_forecaster_proto_rawDescGZIP() []byte {
	file_forecaster_proto_rawDescOnce.Do(func() {
		file_forecaster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_forecaster_proto_rawDesc), len(file_forecaster_proto_rawDesc)))
	})
	return file_forecaster_proto_rawDescData
}

var file_forecaster_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_forecaster_proto_goTypes = []any{
	(*ForecastRequest)(nil),  // 0: forecaster.ForecastRequest
	(*ForecastPoint)(nil),    // 1: forecaster.ForecastPoint
	(*ForecastResponse)(nil), // 2: forecaster.ForecastResponse
	nil,                      // 3: forecaster.ForecastRequest.LabelsEntry
}
var file_forecaster_proto_depIdxs = []int32{
	3, // 0: forecaster.ForecastRequest.labels:type_name -> forecaster.ForecastRequest.LabelsEntry
	1, // 1: forecaster.ForecastResponse.points:type_name -> forecaster.ForecastPoint
	0, // 2: forecaster.Forecaster.Forecast:input_type -> forecaster.ForecastRequest
	2, // 3: forecaster.Forecaster.Forecast:output_type -> forecaster.ForecastResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_forecaster_proto_init() }
func file_forecaster_proto_init() {
	if File_forecaster_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_forecaster_proto_rawDesc), len(file_forecaster_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_forecaster_proto_goTypes,
		DependencyIndexes: file_forecaster_proto_depIdxs,
		MessageInfos:      file_forecaster_proto_msgTypes,
	}.Build()
	File_forecaster_proto = out.File
	file_forecaster_proto_goTypes = nil
	file_forecaster_proto_depIdxs = nil
}
