apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: config-patch.yaml

images:
  - name: kubewise/agent
    newTag: dev
  - name: kubewise/forecaster
    newTag: dev
