apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

configMapGenerator:
  - name: kubewise-agent-config
    behavior: merge
    files:
      - config.yaml=configs/agent-config.yaml

images:
  - name: kubewise/agent
    newTag: dev
  - name: kubewise/forecaster
    newTag: dev
