apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubewise-agent
  namespace: kubewise
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: agent
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: '1'
              memory: 1Gi
        - name: forecaster
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: '2'
              memory: 1Gi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: kubewise-agent-data
