apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - pdb.yaml
  - pvc.yaml

images:
  - name: kubewise/agent
    newName: kubewise/agent
    newTag: v0.3.0
  - name: kubewise/forecaster
    newName: kubewise/forecaster
    newTag: v0.3.0

patches:
  - path: deployment-patch.yaml
