# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import forecaster_pb2 as forecaster__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in forecaster_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ForecasterStub(object):
    """Forecaster provides forward-looking predictions for metric time series.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Forecast = channel.unary_unary(
                '/forecaster.Forecaster/Forecast',
                request_serializer=forecaster__pb2.ForecastRequest.SerializeToString,
                response_deserializer=forecaster__pb2.ForecastResponse.FromString,
                _registered_method=True)


class ForecasterServicer(object):
    """Forecaster provides forward-looking predictions for metric time series.
    """

    def Forecast(self, request, context):
        """Forecast takes a metric history and predicts future values with
        confidence intervals.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ForecasterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Forecast': grpc.unary_unary_rpc_method_handler(
                    servicer.Forecast,
                    request_deserializer=forecaster__pb2.ForecastRequest.FromString,
                    response_serializer=forecaster__pb2.ForecastResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'forecaster.Forecaster', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('forecaster.Forecaster', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Forecaster(object):
    """Forecaster provides forward-looking predictions for metric time series.
    """

    @staticmethod
    def Forecast(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forecaster.Forecaster/Forecast',
            forecaster__pb2.ForecastRequest.SerializeToString,
            forecaster__pb2.ForecastResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
