# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: forecaster.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'forecaster.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x66orecaster.proto\x12\nforecaster\"\xdd\x01\n\x0f\x46orecastRequest\x12\x13\n\x0bmetric_name\x18\x01 \x01(\t\x12\x0e\n\x06values\x18\x02 \x03(\x01\x12\x12\n\ntimestamps\x18\x03 \x03(\x01\x12\x37\n\x06labels\x18\x04 \x03(\x0b\x32\'.forecaster.ForecastRequest.LabelsEntry\x12\x0f\n\x07horizon\x18\x05 \x01(\x05\x12\x18\n\x10interval_seconds\x18\x06 \x01(\x01\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"[\n\rForecastPoint\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\r\n\x05value\x18\x02 \x01(\x01\x12\x13\n\x0blower_bound\x18\x03 \x01(\x01\x12\x13\n\x0bupper_bound\x18\x04 \x01(\x01\"d\n\x10\x46orecastResponse\x12)\n\x06points\x18\x01 \x03(\x0b\x32\x19.forecaster.ForecastPoint\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x15\n\rerror_message\x18\x03 \x01(\t2S\n\nForecaster\x12\x45\n\x08\x46orecast\x12\x1b.forecaster.ForecastRequest\x1a\x1c.forecaster.ForecastResponseB?Z=github.com/lohitkolluri/KubeWise/internal/agent/forecaster/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'forecaster_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z=github.com/lohitkolluri/KubeWise/internal/agent/forecaster/pb'
  _globals['_FORECASTREQUEST_LABELSENTRY']._loaded_options = None
  _globals['_FORECASTREQUEST_LABELSENTRY']._serialized_options = b'8\001'
  _globals['_FORECASTREQUEST']._serialized_start=33
  _globals['_FORECASTREQUEST']._serialized_end=254
  _globals['_FORECASTREQUEST_LABELSENTRY']._serialized_start=209
  _globals['_FORECASTREQUEST_LABELSENTRY']._serialized_end=254
  _globals['_FORECASTPOINT']._serialized_start=256
  _globals['_FORECASTPOINT']._serialized_end=347
  _globals['_FORECASTRESPONSE']._serialized_start=349
  _globals['_FORECASTRESPONSE']._serialized_end=449
  _globals['_FORECASTER']._serialized_start=451
  _globals['_FORECASTER']._serialized_end=534
# @@protoc_insertion_point(module_scope)
