version: '3.8'

services:
  kubewise:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kubewise
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
    environment:
      - MONGODB_ATLAS_URI=mongodb://mongodb:27017
      - MONGODB_DB_NAME=kubewise_db
      - PROMETHEUS_URL=http://prometheus:9090
    depends_on:
      - mongodb
      - prometheus
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    restart: unless-stopped

  # Optional: Add Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  mongodb_data:
  prometheus_data:
  grafana_data:
