global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alert manager configuration (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Rule files (optional)
rule_files: []

# Scrape configurations
scrape_configs:
  # Self-monitoring for Prometheus
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # K8s Anomaly Detector - metrics endpoint
  - job_name: "k8s-anomaly-detector"
    static_configs:
      - targets: ["host.docker.internal:9091"]  # For Docker Desktop on Mac/Windows
      # For Linux hosts, use:
      # - targets: ["172.17.0.1:9091"]  # Docker default gateway

  # NOTE: Uncomment the configurations below when deploying to a Kubernetes cluster

  # Kubernetes API server
  # - job_name: "kubernetes-apiservers"
  #   kubernetes_sd_configs:
  #     - role: endpoints
  #   scheme: https
  #   tls_config:
  #     ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  #   bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  #   relabel_configs:
  #     - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
  #       action: keep
  #       regex: default;kubernetes;https

  # Kubernetes nodes
  # - job_name: "kubernetes-nodes"
  #   kubernetes_sd_configs:
  #     - role: node
  #   scheme: https
  #   tls_config:
  #     ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  #   bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  #   relabel_configs:
  #     - target_label: __address__
  #       replacement: kubernetes.default.svc:443
  #     - source_labels: [__meta_kubernetes_node_name]
  #       regex: (.+)
  #       target_label: __metrics_path__
  #       replacement: /api/v1/nodes/${1}/proxy/metrics

  # Kubernetes pods
  # - job_name: "kubernetes-pods"
  #   kubernetes_sd_configs:
  #     - role: pod
  #   relabel_configs:
  #     - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
  #       action: keep
  #       regex: true
  #     - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
  #       action: replace
  #       target_label: __metrics_path__
  #       regex: (.+)
  #     - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
  #       action: replace
  #       regex: ([^:]+)(?::\d+)?;(\d+)
  #       replacement: $1:$2
  #       target_label: __address__
  #     - action: labelmap
  #       regex: __meta_kubernetes_pod_label_(.+)
  #     - source_labels: [__meta_kubernetes_namespace]
  #       action: replace
  #       target_label: kubernetes_namespace
  #     - source_labels: [__meta_kubernetes_pod_name]
  #       action: replace
  #       target_label: kubernetes_pod_name
