apiVersion: v1
kind: Pod
metadata:
  name: crashloop-pod
spec:
  restartPolicy: Always
  containers:
    - name: crash
      image: busybox
      command: ["sh", "-c", "echo 'Simulating CrashLoopBackOff'; exit 1"]
---
apiVersion: batch/v1
kind: Job
metadata:
  name: failing-job
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: fail
          image: busybox
          command: ["sh", "-c", "echo 'Job failing'; exit 1"]
---
apiVersion: v1
kind: Pod
metadata:
  name: oomkill-pod
  labels:
    app: oomkill-test
spec:
  restartPolicy: Always
  containers:
    - name: memory-hog
      image: polinux/stress
      resources:
        limits:
          memory: "64Mi"  # Very limited memory
          cpu: "100m"
        requests:
          memory: "32Mi"
          cpu: "50m"
      command: ["stress"]
      args: ["--vm", "1", "--vm-bytes", "128M", "--vm-hang", "0"]  # Try to allocate 128MB when limit is 64MB
