apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoring
  labels:
    app: prometheus
  # Optional: Add annotations if needed for service discovery or ingress controllers
  # annotations:
  #   prometheus.io/scrape: 'true'
  #   prometheus.io/port:   '9090'
spec:
  selector:
    app: prometheus # Selects pods with the label 'app: prometheus'
  ports:
    - protocol: TCP
      port: 9090 # Port exposed by the service
      targetPort: 9090 # Port on the Prometheus container
  type: ClusterIP # Exposes the service on a cluster-internal IP. Change to NodePort or LoadBalancer if external access is required.
