apiVersion: v1
kind: Service
metadata:
  name: cadvisor-service
  namespace: monitoring
  labels:
    app: cadvisor
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8080'
spec:
  selector:
    app: cadvisor
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP 