apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: victoria-metrics-pvc
  namespace: monitoring
  labels:
    app: victoria-metrics
spec:
  accessModes:
    - ReadWriteOnce # Suitable for a single pod deployment
  resources:
    requests:
      storage: 20Gi # Updated to match the current allocation
  # storageClassName: standard # Optional: Specify a StorageClass if needed, otherwise uses default
