apiVersion: v1
kind: ServiceAccount
metadata:
  name: custom-exporter
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: custom-exporter-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: custom-exporter
  namespace: monitoring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-exporter
  namespace: monitoring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: custom-exporter
  template:
    metadata:
      labels:
        app: custom-exporter
    spec:
      serviceAccountName: custom-exporter
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - custom-exporter
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: custom-exporter
        image: prom/statsd-exporter:v0.24.0 # Example exporter
        ports:
        - containerPort: 9102
          name: metrics
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /metrics
            port: 9102
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /metrics
            port: 9102
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: custom-exporter
  namespace: monitoring
  labels:
    app: custom-exporter
spec:
  selector:
    app: custom-exporter
  ports:
  - name: metrics
    port: 9102
    targetPort: 9102
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: custom-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: custom-exporter
  endpoints:
  - port: metrics
    interval: 15s
    path: /metrics 