apiVersion: v1
kind: Service
metadata:
  name: victoria-metrics-service
  namespace: monitoring
  labels:
    app: victoria-metrics
spec:
  selector:
    app: victoria-metrics # Selects pods with the label 'app: victoria-metrics'
  ports:
    - protocol: TCP
      port: 8428 # Port the service will listen on
      targetPort: 8428 # Port the container is listening on
      name: http
  type: ClusterIP # Expose the service on a cluster-internal IP
