apiVersion: v1
kind: Pod
metadata:
  name: crashloop-pod
spec:
  restartPolicy: Always
  containers:
    - name: crashloop-container
      image: busybox:latest
      command: ["sh", "-c", "echo 'Crashing now…'; exit 1"]
