replicaCount: 1

image:
  repository: kubewise
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

mongodb:
  uri: ""

nodeSelector: {}

tolerations: []

affinity: {}
